# Jekyll configuration for the Attunement blog
# See https://jekyllrb.com/docs/configuration/options/
title: ΔΔodulating Ɛpsilon
author: Sam Hiatt
email: modulatingepsilon@gmail.com
description: Let's make big ideas matter
theme: minima
sass:
  quiet_deps: true
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Post display settings
show_excerpts: true
excerpt_separator: <!--more-->
future: false
unpublished: false

# Minima theme configuration
minima:
  date_format: "%b %-d, %Y"

# header_pages:
#   - /about.html
#   - /contact.html